apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    heritage: dkube
  name: kafka-pv1
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: datadir-0-dkube-kafka-cp-kafka-0
    namespace: dkube-kafka
  nfs:
    path: /mnt/nfs_share/dkube-104/kafka/kafka-pv1
    server: 192.168.200.161
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    heritage: dkube
  name: kafka-pv2
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: datadir-dkube-kafka-cp-zookeeper-0
    namespace: dkube-kafka
  nfs:
    path: /mnt/nfs_share/dkube-104/kafka/kafka-pv2
    server: 192.168.200.161
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    heritage: dkube
  name: kafka-pv3
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: datalogdir-dkube-kafka-cp-zookeeper-0
    namespace: dkube-kafka
  nfs:
    path: /mnt/nfs_share/dkube-104/kafka/kafka-pv3
    server: 192.168.200.161
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    heritage: dkube
  name: kafka-pv4
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: datadir-0-dkube-kafka-cp-kafka-1
    namespace: dkube-kafka
  nfs:
    path: /mnt/nfs_share/dkube-104/kafka/kafka-pv4
    server: 192.168.200.161
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    heritage: dkube
  name: kafka-pv5
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: datadir-dkube-kafka-cp-zookeeper-1
    namespace: dkube-kafka
  nfs:
    path: /mnt/nfs_share/dkube-104/kafka/kafka-pv5
    server: 192.168.200.161
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    heritage: dkube
  name: kafka-pv6
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: datalogdir-dkube-kafka-cp-zookeeper-1
    namespace: dkube-kafka
  nfs:
    path: /mnt/nfs_share/dkube-104/kafka/kafka-pv6
    server: 192.168.200.161
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    heritage: dkube
  name: kafka-pv7
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: datadir-0-dkube-kafka-cp-kafka-2
    namespace: dkube-kafka
  nfs:
    path: /mnt/nfs_share/dkube-104/kafka/kafka-pv7
    server: 192.168.200.161
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    heritage: dkube
  name: kafka-pv8
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: datadir-dkube-kafka-cp-zookeeper-2
    namespace: dkube-kafka
  nfs:
    path: /mnt/nfs_share/dkube-104/kafka/kafka-pv8
    server: 192.168.200.161
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    heritage: dkube
  name: kafka-pv9
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: datalogdir-dkube-kafka-cp-zookeeper-2
    namespace: dkube-kafka
  nfs:
    path: /mnt/nfs_share/dkube-104/kafka/kafka-pv9
    server: 192.168.200.161
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
